version: '1'

services:
  api:
    image: tinyurl-api:v1.0
    build: ./tinyurl_api
    ports:
      - "4567:4567"
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logs
  mysql:
    image: tinyurl-db:8.0
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "hs"
      MYSQL_USER: "hs"
      MYSQL_PASSWORD: "hs"
    ports:
      - "3306:3306"

